[package]
name = "cli"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
documentation.workspace = true

[[bin]]
name = "subniri"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
cliclack = "0.5.4"
comfy-table = "7.2.2"
daemon.workspace = true
launcher.workspace = true
tokio = { workspace = true, features = ["full"] }
zbus.workspace = true
