[package]
name = "cli"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
documentation.workspace = true

[[bin]]
name = "subniri"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
daemon.workspace = true
modern-terminal = "0.7.0"
