[package]
name = "config"
version.workspace = true
authors.workspace = true
description = "Config helpers for the subniri shell"
edition.workspace = true
documentation.workspace = true

[lints]
workspace = true

[dependencies]
async-stream.workspace = true
config-macros = { version = "0.0.1", path = "../config-macros" }
config-traits = { version = "0.0.1", path = "../config-traits" }
dirs = "6.0.0"
futures.workspace = true
garde = { version = "0.22.1", features = ["derive"] }
jiff = "0.2.24"
kdl = { version = "6.5.0", features = ["v1-fallback"] }
miette = { version = "7.6.0", features = ["fancy"] }
notify = "8.2.0"
tokio = { workspace = true, features = ["sync", "time"] }
url = "2.5.8"
