[package]
name = "logout"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
documentation.workspace = true

[[bin]]
name = "iceout"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
iced.workspace = true
iced_layershell.workspace = true
futures.workspace = true
log.workspace = true
neo-widgets.workspace = true
nix.workspace = true
serde.workspace = true
zbus.workspace = true
zvariant.workspace = true
