[package]
name = "bar"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Bar for subniri shell"
documentation.workspace = true

[[bin]]
name = "polarbar"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
async-channel.workspace = true
async-stream.workspace = true
bluer.workspace = true
config.workspace = true
daemon.workspace = true
float-ord.workspace = true
futures.workspace = true
iced.workspace = true
iced_layershell.workspace = true
iced_runtime.workspace = true
image.workspace = true
jiff.workspace = true
kdl.workspace = true
libpulse-binding.workspace = true
libpulse-tokio.workspace = true
log.workspace = true
lru.workspace = true
mprizzle.workspace = true
neo-widgets.workspace = true
niri-ipc.workspace = true
nix.workspace = true
nmrs.workspace = true
pipewire-native = "0.1.4"
pipewire-native-spa = "0.1.4"
reqwest.workspace = true
serde_json.workspace = true
small-map.workspace = true
tokio.workspace = true
url.workspace = true
wayland-client.workspace = true
zbus.workspace = true
