[package]
name = "file-manager"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
documentation.workspace = true

[[bin]]
name = "fileberg"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
clap = { workspace = true, features = ["derive"] }
dirs = "6.0.0"
iced.workspace = true
iced_runtime.workspace = true
ignore = "0.4.26"
log.workspace = true
mime = "0.3.17"
neo-widgets.workspace = true
serde.workspace = true
tokio.workspace = true
undo = { version = "0.52.0", features = ["serde"] }
xdg-mime = "0.4.0"
zbus.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
